### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by poxyran** [sam-b/ioctl_plugin#1]
Hi Sam!, I'm using the plugin in IDA 9.5 and, even though the IOCTLs are showed in the log window, I get this error:

{{{
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.95/plugins/ioctl_plugin.py", line 254, in activate
    DisplayIOCTLSForm()
  File "C:/Program Files (x86)/IDA 6.95/plugins/ioctl_plugin.py", line 34, in **init**
    "form_change": Form.FormChangeCb(self.form_change),
  File "C:\Program Files (x86)\IDA 6.95\python\ida_kernwin.py", line 4255, in **init**
    self.arg = _FORMCHGCB_T(self.helper_cb)
TypeError: 'NoneType' object is not callable
}}}

Any idea?

**Comment by sam-b** [comment]
Weird - I couldn't get this to replicate, I'll see if I have an older IDA installer laying about to test on :/

**Comment by sam-b** [comment]
@poxyran slowest follow up ever (life :O) but let me know if the new version I just pushed is still bugging out
